// src/lib/components/Profile/Profile.svelte
<script lang="ts">
	import { profiles, type ProfileData } from '$lib/data/profiles';
	import { getEvent } from '$lib/utils/nostr';
	import { onMount } from 'svelte';
	import ProfileMenu from './ProfileMenu.svelte';

	export let npubHex: string;
	export let imageOnly = false;
	export let detail = false;
	export let to = `/profile/${npubHex}`;

	let profile: ProfileData | undefined = { name: 'loading' };

	onMount(async () => {
		const p = $profiles.get(npubHex);
		if (p) return (profile = p);
		const event = await getEvent({ kinds: [0], authors: [npubHex] });
		if (!event) return (profile = { name: 'error' });
		const parsed = JSON.parse(event.content);
		profiles.update((updater) => updater.set(npubHex, parsed));
		profile = parsed;
	});

	$: [name, domain] = (profile?.nip05 || `@${profile?.name || ''}`).split('@');
	$: maxWitdh =
		name.length > 20
			? domain.length > 10
				? 'max-w-[5em]'
				: 'max-w-[10em]'
			: '';
</script>

{#key profile}
	<div>
		{#if detail}
			{#if profile?.banner}
				<div class="mb-12 max-h-[30vh] overflow-clip flex items-center">
					<img class="object-cover w-full" src={profile.banner} alt="" />
				</div>
			{/if}
		{/if}
		<div class="flex justify-between">
			<a class="flex gap-2 text-inherit visited:text-inherit w-fit" href={to}>
				<img
					class="w-12 h-12 rounded"
					src={profile?.picture}
					alt={profile?.name}
				/>
				{#if !imageOnly}
					<div>
						<div>
							{#if profile?.display_name}
								{profile.display_name}
								{#if profile?.name}
									<span class="text-xs text-gray-500">@{profile.name}</span>
								{/if}
							{:else}
								{profile?.name}
							{/if}
						</div>
						<div class="flex mt-2 text-xs text-gray-500">
							<div class="truncate ... {maxWitdh}">
								{name}
							</div>
							<div>@</div>
							<div>{domain}</div>
						</div>
					</div>
				{/if}
			</a>
			{#if detail}
				<ProfileMenu {npubHex} />
			{/if}
		</div>

		{#if detail}
			<div>
				<div class="mt-4 break-words">{profile?.about || ''}</div>
				{#if profile?.website}
					<a
						class="mt-2 break-words"
						href={profile.website}
						target="_blank"
						rel="noopener noreferrer"
					>
						{profile.website}
					</a>
				{/if}
			</div>
		{/if}
	</div>
{/key}

// src/components/Profile.tsx
import type { MetadataEvent } from '@/lib/nostr/kinds/0'
import { Avatar, AvatarFallback, AvatarImage } from '@/shadcn-ui/components/ui/avatar'
import { Button } from '@/shadcn-ui/components/ui/button'

interface Props {
  content?: MetadataEvent['content']
}

export default function Profile({ content }: Props) {
  const displayName = content?.display_name || content?.name || ''
  const name = content?.nip05?.replace('_@', '') || content?.name || ''

  return (
    <div>
      <div className="bg-muted-foreground z-0 h-60">
        {content?.banner && (
          <img
            src={content.banner}
            alt="Banner"
            className="h-full w-full object-cover"
            loading="lazy"
            decoding="async"
          />
        )}
      </div>
      <Avatar className="m-2 -mt-15 size-30">
        <AvatarImage
          src={content?.picture}
          loading="lazy"
          decoding="async"
        />
        <AvatarFallback>
          {displayName.slice(0, 2).toUpperCase()}
        </AvatarFallback>
      </Avatar>
      <div className="p-4">
        <div className="flex justify-between">
          <div>
            <div className="text-2xl">{displayName}</div>
            <div className="text-muted-foreground">
              {name}
            </div>
          </div>
          <Button disabled>Follow</Button>
        </div>
        <div>
          <p>{content?.about}</p>
        </div>
      </div>
    </div>
  )
}
